groupchat: fix traceback on clicking on a user
This fixes a bug introduced in trunk@3128. userSingleClicked threw a traceback:
  TypeError: first argument of unbound method QListWidget.mouseReleaseEvent()
  must be a QListWidget instance