Fix referencing a deleted C++ object from typing notify
Several people saw this error appear:

Traceback (most recent call last):
File "/usr/share/jabbim/widgets/abstractchatwidget.py", line 354, in
paused
	if self.text==unicode(self.toPlainText()):
RuntimeError: underlying C/C++ object has been deleted

I found a reproducer:
1. Open a chat with someone
2. Write something to him
3. Close the chat window quickly (before the typing notification kicks
in and sends out the "paused" state).

This causes the QTimer to trigger and run its callback, but the object
the callback references exists no more.

Fix it by defining a parent for the QTimer so when the window is
destroyed, the timer is killed too.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=528370