fix a common (but harmless) traceback
This was one of the most frequent tracebacks, it happened whenever a
tooltip was requested for anything which was not a contact (a group or
separator).

File ".../widgets/rosterLiveWidget.py", line 872, in event
    jid=item.jid
AttributeError: groupItem instance has no attribute 'jid'

It caused no problems, just spammed the log.